#===============================================================================
# Copyright 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

# Shared setup for every plugin's standalone CMake project in this
# directory -- factored out so a new plugin copied from matmul_template/
# doesn't also copy (and drift from) this boilerplate. A plugin's own
# CMakeLists.txt should, in this order:
#   cmake_minimum_required(VERSION 3.16)
#   project(<name> LANGUAGES CXX)
#   include(${CMAKE_CURRENT_SOURCE_DIR}/../common.cmake)
#   add_library(<target> SHARED <sources>)
#   # ... plugin-specific target setup (e.g. static-archive linking) ...
#   plugin_common_setup(<target>)

if(NOT ONEDNN_SOURCE_DIR)
    message(FATAL_ERROR
        "ONEDNN_SOURCE_DIR must point at the root of the oneDNN fork this "
        "plugin is built against (the directory containing src/ and "
        "include/).")
endif()
if(NOT ONEDNN_BUILD_DIR)
    message(FATAL_ERROR
        "ONEDNN_BUILD_DIR must point at that oneDNN fork's already-"
        "configured build directory (for generated headers such as "
        "dnnl_config.h/dnnl_version.h) and its built dnnl library.")
endif()

set(ONEDNN_PLUGIN_LINK_MODE "ARCHIVE" CACHE STRING
    "Plugin internal-symbol link mode: ARCHIVE or HOST")
set_property(CACHE ONEDNN_PLUGIN_LINK_MODE PROPERTY STRINGS ARCHIVE HOST)
string(TOUPPER "${ONEDNN_PLUGIN_LINK_MODE}" ONEDNN_PLUGIN_LINK_MODE)
if(NOT ONEDNN_PLUGIN_LINK_MODE STREQUAL "ARCHIVE"
        AND NOT ONEDNN_PLUGIN_LINK_MODE STREQUAL "HOST")
    message(FATAL_ERROR
        "ONEDNN_PLUGIN_LINK_MODE must be ARCHIVE or HOST, got "
        "'${ONEDNN_PLUGIN_LINK_MODE}'.")
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

if(NOT CMAKE_CXX_FLAGS MATCHES "-fsycl")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl")
endif()

# Must match the NDEBUG-ness of the oneDNN build whose object code
# ../make_archives.sh packages below. That build is Release (NDEBUG
# defined), so its assert()s -- including utils::downcast()'s
# `assert(dynamic_cast<...>(...) == ...)` -- compile to nothing and emit no
# dynamic_cast/typeinfo references anywhere in the archive. If a plugin
# doesn't also define NDEBUG, any downcast<T*>(...) call in its own code
# compiles a live dynamic_cast requiring T's typeinfo, which was never
# generated by the (asserts-stripped) main build -- surfaces as "undefined
# symbol: typeinfo for ..." at dlopen time, not a real missing-
# implementation gap. Applied here, not per-plugin, since it's required by
# every plugin linking the shared archive below, not just ones that
# obviously downcast.
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()
add_compile_definitions(NDEBUG)

# Call once, after add_library(<target> ...), to apply the include paths,
# dnnl link, optional static archive link, and visibility settings every
# plugin needs identically.
function(plugin_common_setup target)
    target_include_directories(${target} PRIVATE
        ${ONEDNN_SOURCE_DIR}/src
        ${ONEDNN_SOURCE_DIR}/include
        ${ONEDNN_BUILD_DIR}/include
    )

    find_library(ONEDNN_LIB
        NAMES dnnl
        PATHS ${ONEDNN_BUILD_DIR}/src ${ONEDNN_BUILD_DIR}
        NO_DEFAULT_PATH
    )
    if(NOT ONEDNN_LIB)
        message(FATAL_ERROR
            "Could not find the built dnnl library under ${ONEDNN_BUILD_DIR}. "
            "Build oneDNN itself first.")
    endif()
    target_link_libraries(${target} PRIVATE ${ONEDNN_LIB})

    if(ONEDNN_PLUGIN_LINK_MODE STREQUAL "ARCHIVE")
    # oneDNN's own build compiles everything with -fvisibility=internal
    # (cmake/platform.cmake), so internal C++ symbols a plugin needs (e.g.
    # memory_storage_t, or even plain pd_t helpers like attr_scales_ok())
    # have no entry in libdnnl.so's *dynamic* symbol table -- dlopen/dlsym
    # can't see them at load time, even though the target_link_libraries
    # above resolves them fine at this plugin's own link time (a *static*
    # resolution against the .so's on-disk symbol table, not a promise
    # those symbols are dynamically exported for another loader to find
    # later). This isn't specific to any one plugin's kernel-access style --
    # confirmed the hard way when even matmul_template's generic,
    # kernel-independent scales_ok() pulled in an unresolved internal
    # symbol (rnn_create_time_scales_t::set_single_scale) with no dlopen
    # error text beyond "(null)". So every plugin here statically links the
    # internal oneDNN object code it might need, packaged as a .a archive
    # by the shared ../make_archives.sh from object files the main oneDNN
    # build already compiled (no recompile). Defaults to
    # ONEDNN_BUILD_DIR/archives -- the same path make_archives.sh writes to
    # when invoked as `make_archives.sh <ONEDNN_BUILD_DIR>`, so there's one
    # path to keep in sync, not two independently-hardcoded ones.
    #
    # target_link_libraries (not target_link_options) so the archive lands
    # AFTER this target's own object file(s) on the final link line -- ld
    # only pulls archive members in to satisfy symbols already outstanding
    # at the point it reaches the archive, so it must come after whatever
    # references those symbols, not before.
    set(PLUGIN_ONEDNN_ARCHIVE_DIR "${ONEDNN_BUILD_DIR}/archives" CACHE PATH
        "Directory of .a archives built by ../make_archives.sh from ONEDNN_BUILD_DIR's object files")
    target_link_libraries(${target} PRIVATE
        -Wl,--start-group ${PLUGIN_ONEDNN_ARCHIVE_DIR}/libdnnl_full.a -Wl,--end-group
    )
    else()
        # HOST mode requires a matching -DDNNL_NATIVE_PLUGIN_HOST=ON build.
        # No oneDNN object archive is linked into the plugin; unresolved
        # native C++ symbols must resolve from the host libdnnl.so.
        if(UNIX AND NOT APPLE)
            target_link_options(${target} PRIVATE -Wl,--no-undefined)
        endif()
    endif()

    set_target_properties(${target} PROPERTIES
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON
    )
endfunction()
