/*******************************************************************************
* Copyright 2026 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

// AUTO-GENERATED by update_kernel.sh from:
//   /c/workspaces/kf3/kernelfoundry.kernel-eval/tasks/onednn/matmul_relu/kernel.sycl
// Do not hand-edit -- rerun update_kernel.sh after kernel.sycl's evolved
// region changes instead. See that script for what it does and why.

#include <sycl/sycl.hpp>

// [EVOLVE_START]

inline void sycl_kernel(sycl::queue &q, const float* A,
                 const float* B,
                 float* C,
                 int M, int K, int N) {

    // add kernel implementation here
}
// [EVOLVE_END]
