#!/usr/bin/env bash
#*******************************************************************************
# Copyright 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*******************************************************************************

# Regenerates kf_kernel.sycl.hpp from KF's real, evolving kernel.sycl.
# This is the actual "intake" step: point it at KF's task file, it lifts
# the [EVOLVE_START]/[EVOLVE_END] region out verbatim and rewrites this
# plugin's kf_kernel.sycl.hpp. Iterating on the kernel is then:
#
#   ./update_kernel.sh /path/to/kernel.sycl && cmake --build build
#
# Today, KF's kernel.sycl fetches its own SYCL queue inside the evolved
# region via a PyTorch-only call (c10::xpu::getCurrentXPUStream().queue()),
# which can't compile here -- this plugin has no libtorch, and a
# oneDNN-submitted kernel should use the stream oneDNN picked for this
# operation, not reach into PyTorch's global stream state. Until KF's
# kernel.sycl adopts the proposed convention change (pass the queue in as
# sycl_kernel()'s first parameter instead of fetching it internally --
# see kf_kernel.sycl.hpp's header comment), this script also does that
# one, purely mechanical rewrite. Once that convention lands upstream,
# the STRIP/REWRITE step below becomes a no-op and can be deleted -- the
# extraction alone will already produce a compilable header.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 /path/to/kernelfoundry.kernel-eval/tasks/<task>/kernel.sycl" >&2
    exit 1
fi

src="$1"
out_dir="$(cd "$(dirname "$0")" && pwd)"
out="$out_dir/kf_kernel.sycl.hpp"

if [ ! -f "$src" ]; then
    echo "error: $src not found" >&2
    exit 1
fi

evolve_region="$(sed -n '/\[EVOLVE_START\]/,/\[EVOLVE_END\]/p' "$src")"
if [ -z "$evolve_region" ]; then
    echo "error: no [EVOLVE_START]/[EVOLVE_END] region found in $src" >&2
    exit 1
fi

# STRIP/REWRITE (delete once KF's kernel.sycl takes `q` as a parameter):
#   - drop the PyTorch-only #include
#   - drop the plain <sycl/sycl.hpp> include (already emitted in the
#     header below -- kept here in kernel.sycl today only because the
#     internal queue-fetch line below needs it)
#   - drop the internal queue-fetch line
#   - add `sycl::queue &q, ` as sycl_kernel()'s first parameter, and mark
#     it `inline` (this header may end up included from more than one
#     translation unit)
rewritten="$(printf '%s\n' "$evolve_region" \
    | grep -v '#include <c10/xpu/XPUStream.h>' \
    | grep -v '#include <sycl/sycl.hpp>' \
    | grep -v 'c10::xpu::getCurrentXPUStream' \
    | sed -E 's/void sycl_kernel\(/inline void sycl_kernel(sycl::queue \&q, /')"

{
    cat <<HEADER
/*******************************************************************************
* Copyright 2026 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

// AUTO-GENERATED by update_kernel.sh from:
//   $src
// Do not hand-edit -- rerun update_kernel.sh after kernel.sycl's evolved
// region changes instead. See that script for what it does and why.

#include <sycl/sycl.hpp>

HEADER
    printf '%s\n' "$rewritten"
} > "$out"

echo "wrote $out (from $src)"
